### ISSUE TITLE
ordenação do list com problemas

### ISSUE THREAD

**Issue by luizaugustosg** [GUMGA/components#100]
Depois de fazer uma busca no gumgaSearch, se clicar no título de alguma coluna do list para ordenar, ele limpa a busca e ordena todos os resultados ao invés de ordenar o resultado da busca.

Estou usando a versão 1.1.8

**Comment by igorsantana** [comment]
@luizaugustosg Isto não é um bug da ordenação da list. Este é o comportamento do Framework Gumga **no backend**. Como o backend é stateless, ele não guarda o estado atual da requisição. Tem meios de se fazer isto modificando os atributos da query do GumgaRest, mas aí vai de cada desenvolvedor . Caso queira ver como funciona a busca simples/avançada, dê uma olhada [aqui](https://github.com/GUMGA/components/blob/v1.1.x_stable/src/services/Rest/Rest.js). Eu sei que a documentação não tá uma das melhores possíveis, mas vamos arrumar isso. :sweat_smile:
