### ISSUE TITLE
Colunas <GumgaList>

### ISSUE THREAD

**Issue by wrquessada** [GUMGA/components#101]
A apresentação das colunas deveriam ter maior destaque na apresentação em relação as informações preenchidas. (outra cor, realçadas, etc...)

**Comment by igorsantana** [comment]
@wrquessada Se puder nos dar um exemplo de tabelas que tem um visual legal! Lembrando que nós usamos o bootstrap como padrão no nosso CSS.

**Comment by igorsantana** [comment]
Continuaremos seguindo o padrão do css.
