### ISSUE TITLE
Ordenação Padrão do List

### ISSUE THREAD

**Issue by luizaugustosg** [GUMGA/components#103]
Na documentação não existe nada falando que a ordenação padrão do list pode ser decrescente, os parâmetros aceitos são somente o campo. É possível a ordenação ser padrão ou o componente não tem essa funcionalidade?

**Comment by igorsantana** [comment]
@luizaugustosg Realmente, não temos a opção ainda de ordernar desc por padrão. Só asc. Não sei se isso seria prioridade para colocar logo pra próxima semana no backlog, o que você acha?

**Comment by luizaugustosg** [comment]
Pra mim não é prioridade, não precisa ser na próxima semana não.

**Comment by igorsantana** [comment]
Ok, vou fechar a issue e assim que tiver notícias de quando será alterado no sprint, volto a abrir.
