### ISSUE TITLE
Erro ao limpar pesquisa do componente gumga-many-to-many

### ISSUE THREAD

**Issue by renanceratto** [GUMGA/components#108]
No componente gumga-many-to-many ao digitar uma pesquisa na esquerda e depois apagar todo filtro, ocorre o erro

{"code":"InvalidDataAccessApiUsageException","message":"Error on operation","details":"Para realizar a search deve se informar pelo menos um campo a ser pesquisado.","data":null,"fieldErrors":[]}

Erro aparece no console.
No cliente aparece "internal server error"

**Comment by igorsantana** [comment]
Não é erro de componente.
