### ISSUE TITLE
Responsividade no List

### ISSUE THREAD

**Issue by renanceratto** [GUMGA/components#110]
Responsividade da lista semelhante ao que é apresentado pelo "datatable" do primefaces
http://www.primefaces.org/showcase/ui/misc/responsive.xhtml

Colunas não são legais em telas muito estreitas. :)

**Comment by igorsantana** [comment]
@renanceratto Realmente temos que dar uma estudada na list, mas por enquanto está no padrão bootstrap. Vou pedir pra colocar no backlog!
