### ISSUE TITLE
Filter no list

### ISSUE THREAD

**Issue by luizaugustosg** [GUMGA/components#114]
Gostaria de saber como eu posso aplicar um filter nos valores de uma coluna do list, além de onde eu devo declarar esse filter.

**Comment by igorsantana** [comment]
@luizaugustosg não entendi sua dúvida cara. É um filter do tipo, filtrar os dados de acordo com um input, ou um filter visual que coloca no html do tipo: `{{$value | currency}}`?

**Comment by luizaugustosg** [comment]
É um filter visual para a coluna do CNPJ.

2015-10-01 17:46 GMT-03:00 Igor Santana notifications@github.com:

**Comment by igorsantana** [comment]
@luizaugustosg então é só aplicar no html normal ué, só tem que configurar através do tableConfig do objeto de configuração da tabela.
