### ISSUE TITLE
Gumga List, atualização do selectedValues

### ISSUE THREAD

**Issue by guiseek** [GUMGA/components#118]
Quando selecionamos uma linha na List e removemos, é feita a chamada na API,  remove a linha da lista mas não remove do selectedValues. No caso de marcar outra linha e remover ele da 404 na chamada da API por tentar executar o DELETE no marcado e no outro que já havia sido removido.
Temos que atualizar o selectedValues.

**Comment by igorsantana** [comment]
Não se aplica, é um comportamento do $populate.
