### ISSUE TITLE
AdvancedSearch: Operador 'AND' residual causando erro

### ISSUE THREAD

**Issue by marcostrevisan** [GUMGA/components#119]
No componente de pesquisa avançada, se adiciono dois campos (Campo1 AND Campo2) e em seguida removo o primeiro campo, o AND continua presente (AND Campo2) e é enviado para API, causando erro.

**Comment by igorsantana** [comment]
Em qual versão você tá usando?

**Comment by marcostrevisan** [comment]
Versão 1.1.12

**Comment by guiseek** [comment]
Já foi corrigido @marcostrevisan, vou lançar um novo release com a correção.

**Comment by marcostrevisan** [comment]
Entendi, blz!
