### ISSUE TITLE
GumgaList: Ao alterar selectedValues, as seleções não são atualizadas na tela

### ISSUE THREAD

**Issue by marcostrevisan** [GUMGA/components#130]
Ao alterar selectedValues, as seleções não são atualizadas na tela. Ex: $scope.selectedValues = [] não desmarca as seleções.

**Comment by igorsantana** [comment]
Não sei se isso é um bug, o comportamento do selectedValues serve para apenas disponibilizar ao escopo em que o componente está os valores que o usuário selecionou.

**Comment by igorsantana** [comment]
Não é um bug, o selectedValues é uma variável que apenas expõe o comportamento da tabela e, como não houve nenhum comentário pedindo para que isto seja uma nova feature, a issue será fechada.
