### ISSUE TITLE
Gumga-list instancia objetos que contém o campo indicado em "data"

### ISSUE THREAD

**Issue by marcostrevisan** [GUMGA/components#135]
Quando o atributo "data" é associado a um atributo de algum objeto (ex: selectedCategory.marketPlaces), o gumga-list instancia o objeto (no caso, selectedCategory) e cria um atributo com valor de array vazio (no caso, selectedCategory = { marketPlaces: [ ] }), o que gera resultados indesejados (dificulta testar se selectedCategory está instanciado adequadamente ou foi instanciado pelo gumga-list).

**Comment by igorsantana** [comment]
Foi selecionado para este sprint :smile:

**Comment by igorsantana** [comment]
De acordo com uma conversa com o @marcostrevisan, vimos que este comportamento não está errado e, portanto, não deve ser investigado mais a fundo.
