### ISSUE TITLE
Alerts aparecem por trás de modais

### ISSUE THREAD

**Issue by marcostrevisan** [GUMGA/components#143]
Quando uma modal se encontra aberta, os alerts produzidos pelo componente GumgaAlert aparecem por trás dela, prejudicando a visualização do conteúdo das mensagens.

**Comment by igorsantana** [comment]
Não temos data definida de entrega deste componente, talvez irá evoluir para um refactory do componente como um todo, já que estamos utilizando um plugin do jQuery.
