### ISSUE TITLE
Paginação não funciona em pesquisa avançada

### ISSUE THREAD

**Issue by marcostrevisan** [GUMGA/components#147]
Quando uma pesquisa avançada é realizada a mudança de página gera erro. Aparentemente, o método getAdvancedSearch  apaga os param da query, de forma que a requisição get vai apenas com a hql no campo 'aq' e 'NaN' no campo 'start'.

**Comment by igorsantana** [comment]
@marcostrevisan já achei o erro e vou fazer colocar no backlog pra resolver, quando corrigir aviso aqui.

**Comment by guiseek** [comment]
@marcostrevisan Legal! estou fazendo umas melhorias no componente search, e já vamos colocar pra resolver neste próximo sprint. Vamos conversar pra alinhar o solução.
