### ISSUE TITLE
Ocultar itens do menu

### ISSUE THREAD

**Issue by luizaugustosg** [GUMGA/components#216]
Uma sugestão de melhoria seria o presentation mostrar no menu lateral, somente os módulos em que o usuário tiver acesso.
Por exemplo, se a aplicação tem os módulos A,B e C, porém o usuário logado só tem permissão no módulo A, ocultar as entradas dos outros módulos ao invés de deixar disponível e quando o usuário entrar no módulo dar um erro de permissão.

**Comment by guiseek** [comment]
Opa, desculpe a demora @luizaugustosg! mas isso é possível já, a validação é feita com a propriedade key dos objetos adicionados com o atributo menu-url, aparecerão somente os itens, se constar no array de string informado com o atributo keys-url. a API deve estar preparada pra trabalhar desta forma, se estiver usando o segurança, o @munifgebara pode dar um help também. valeu, abraço.
