### ISSUE TITLE
Bugs no List

### ISSUE THREAD

**Issue by luizaugustosg** [GUMGA/components#83]
O componente Gumga List apresenta os seguintes bugs:
- A ordenação não funciona corretamente. Ao clicar num dos labels da tabela, ele ordena de forma crescente, porém se clicar outra vez ele não realiza a busca de forma decrescente. Ele cria a requisição, mas não passa o sortDir;
- Ao utilizar o parametro class="bordered" ele não aplica na tabela, a classe da tabela fica "table bordered ng-scope" ao invés de "table table-bordered ng-scope";
- Não é possível remover os checkbox das linhas;

**Comment by igorsantana** [comment]
Qual versão você está usando?

Quanto ao segundo item:
você precisa adicionar a classe table-bordered, não só bordered. Usamos o padrão do bootstrap, e no bootstrap uma table com borda ficaria "table table-bordered".

**Comment by luizaugustosg** [comment]
Estou a usando a versão 1.1.5.

E quanto o segundo item, eu estava utilizando o mesmo padrão da table
antiga, pois na documentação do List não fala nada sobre qual padrão usar.

2015-09-08 17:05 GMT-03:00 Igor Santana notifications@github.com:

**Comment by igorsantana** [comment]
Agora seguimos o padrão do bootstrap :smile: 
Caso consiga (e queira) ajudar com a documentação, só abrir um pull-request na branch que você está usando (que no caso, seria 1.1.x_dev) com as alterações na documentação!

**Comment by guiseek** [comment]
Luiz, no objeto de configuração do GumgaList já é possível remover a opção de checkboxes.

**Comment by luizaugustosg** [comment]
Como eu faço para tirar os checkbox? E foi resolvida a questão da ordenação?

**Comment by igorsantana** [comment]
@luizaugustosg 
Você atualizou a versão? A atual é a 1.1.8.
Na versão atual, a ordenação está sim funcionando. Para que ela funcione, é necessário passar uma função:

``` js
sort="sortFunction(field,dir)"
```

:boom: **Os parâmetros precisam ser field, dir!!!**:boom: 

A list, por padrão, já vem sem os checkbox. Para colocar os checkbox, você precisa colocar o atributo "checkbox" com o valor true no objeto de configuração da tabela.

**Comment by luizaugustosg** [comment]
Deu certo aqui, só mais uma coisa, como eu faço pra pegar o id do objeto que eu to selencionando no momento? No gumgaTable eu usava entity.id, como eu faço no list?

**Comment by igorsantana** [comment]
@luizaugustosg $value.id
