### ISSUE TITLE
BreadCrumb

### ISSUE THREAD

**Issue by wrquessada** [GUMGA/components#99]
Permitir personalizar essa opção, facilitando ao usuário final de uma aplicação construida o pleno entendimento desta opção disponibilizada.

**Comment by igorsantana** [comment]
@wrquessada Você consegue pensar em algum exemplo de personalização? Nós chegamos a pensar em criar um arquivo de configuração para isto, ou algum objeto javascript, mas não batemos um ponto nisso e não caiu no sprint ainda. Caso tenha alguma idéia, nos ajude! @guiseek @mateusmiranda1515

**Comment by wrquessada** [comment]
No meu ponto de vista, teria que ser algo simples, tipo gumga-list, opção "title", por exemplo já mataria a questão....

**Comment by igorsantana** [comment]
@wrquessada  Mas tem que pensar que tem que ser genérica. Se você conseguir nos dê um exemplo.

**Comment by wrquessada** [comment]
Pessoalmente poderemos evoluir neste assunto e chegar denominador. Ao fazer uma framework, acredito sim que temos que pensar em reusabilidade, generico, etc..., mas ao desenvolver uma aplicacao, fico pensando onde mais usaria isso em outro lugar do sistema e nao consegui visualizar, se puder dar algum exemplo, podera nos ajudar....

**Comment by igorsantana** [comment]
@wrquessada A questão não é usar em outros lugares do sistema, é usar em qualquer sistema! Mas assim que entrar em análise para desenvolvimento, volto a abrir essa issue e te passo a análise.

**Comment by wrquessada** [comment]
Tranquilo, voltamos a conversar...

abs

Em 22 de setembro de 2015 09:09, Igor Santana notifications@github.com
escreveu:
